with STG_PREDICTIT_CONTRACTS as (
    select 
        *
    from RAW.PUBLIC.STG_PREDICTIT_CONTRACTS
)
select
    id,
    PREDICTIT_CONTRACT_ID,
    IMAGE,
    END_DATE,
    CONTRACT_NAME,
    CONTRACT_STATUS_NAME,
    CONTRACT_SHORT_NAME,
    LAST_TRADE_PRICE,
    BEST_BUY_YES_COST,
    BEST_BUY_NO_COST,
    BEST_SELL_YES_COST,
    BEST_SELL_NO_COST,
    LAST_CLOSE_PRICE,
    DATEID
from 
    STG_PREDICTIT_CONTRACTS